"""empty message

Revision ID: 13225292e0b3
Revises: be2fbee2d428
Create Date: 2021-01-24 18:14:13.750665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13225292e0b3'
down_revision = 'be2fbee2d428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums_groups',
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums_groups')
    # ### end Alembic commands ###
