"""empty message

Revision ID: 19833ea4dbd2
Revises: 9de5c267a730
Create Date: 2021-01-21 22:34:14.205523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19833ea4dbd2'
down_revision = '9de5c267a730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
