"""empty message

Revision ID: 3af2cdf261e9
Revises: 96863d8ace7a
Create Date: 2021-11-28 22:38:09.562313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af2cdf261e9'
down_revision = '96863d8ace7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('albums', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_albums_end_date'), 'albums', ['end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_end_date'), table_name='albums')
    op.drop_column('albums', 'start_date')
    op.drop_column('albums', 'end_date')
    # ### end Alembic commands ###
